### ISSUE TITLE
Roadmap proposals

### ISSUE THREAD

**Issue by addyosmani** [guess-js/guess#50]
#### Features / Ease of use
- [x] Improve Guess API #42 
- [ ] Re-introduce chunk clustering #6 
- [ ] Cache the OAuth2 access token #12 

#### Code-sharing
- [ ] Investigate better code-sharing between bundling/non-bundling solutions 
- [ ] Investigate code re-use with 3P providers (e.g IIH Nordic)

#### Machine Learning
- [x] Evaluate using neural networks vs current markov chain approach
- [x] Evaluate using [LSTM](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)

#### Community
- [x] Micro-site 
- [x] Codelab: Data-driven loading
- [ ] Codelab: Data-driven bundling 

### Integrations
- [x] Parser: return all routes for an Angular app #44 
- [ ] Parser: support for Vue.js
- [x] Parser: support for Next.js

Any other ideas we want to consider? @mgechev @khempenius @KyleAMathews @MarkEdmondson1234

**Comment by mgechev** [comment]
We should also see how we can extract deeper navigation paths (more than 2 levels) in GA. Currently, we're able to get `previousPagePath` & `pagePath`. Probably this could be considered as subtask for:

> Evaluate using LSTM

**Comment by mgechev** [comment]
One more thing which I'm experimenting with is a parser which empowers partial evaluation with prepack. This will allow us to collect metadata from a broader range of apps.

**Comment by mgechev** [comment]
@KyleAMathews I'll open a PR with this right after we merge [this](https://github.com/guess-js/guess/pull/57).

What do you think about:

```ts
GuessPlugin({
  GA: 'XXXXXX',
  token: JSON.parse(require('./credentials.json')),
  ...
})
```

If `token` is not specified, we use the browser.

**Comment by addyosmani** [comment]
I've heard folks are also interested in a demonstration of how Guess can be used with either service workers or service worker libraries such as Workbox.

In an app where you may already be using service workers to precache/prefetch or fully using PRPL, having a clear story there would be nice. I actually think we're not a million miles away from explaining this through Gatsby.

As mentioned in another issue, I think there's a story in using our predictions to just fetch data/JSON for routes that may not be clear to folks today.

**Comment by mgechev** [comment]
I think we can close the issue for now, we have descent part of the roadmap already in.
